[global]
hideTopBar = true

[browser]
gatherUsageStats = false

[ui]
hide_streamlit_markers = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3366CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
